spring:
  application:
    name: lupus
  datasource:
    url: jdbc:h2:mem:lupus;DB_CLOSE_DELAY=-1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

lupus:
  game:
    min-players: 4
    max-players: 30
